// Compiled normal UI with polling on. Native owners/PG; all inputs/model answers are synthetic.
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { chromium } = require("playwright");
const origin = process.env.QTRADES_BROWSER_QA_ORIGIN || "http://127.0.0.1:58996";
const directory = process.env.QTRADES_BROWSER_QA_OUTPUT;
const token = process.env.QTRADES_BROWSER_QA_TOKEN;
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

(async () => {
  assert(directory && token);
  const address = new URL(origin);
  assert.equal(address.hostname, "127.0.0.1");
  assert(!["8780", "5432", "54544"].includes(address.port));
  fs.mkdirSync(directory, { recursive: false });
  const groups = [], errors = [], requests = [], external = [];
  const receipt = { scope: "Compiled product, unsuppressed polling, native PG/worker/scanner; synthetic inputs, clock and model callbacks", groups, errors, requests, external, model_calls: 0, operating_acceptance: false };
  const save = (name, value) => fs.writeFileSync(path.join(directory, name), JSON.stringify(value, null, 2));
  let browser, context, page, phase = "startup", failure;
  const deadline = setTimeout(() => { receipt.deadline_reached = true; if (context) void context.close(); }, 360000);
  try {
    browser = await chromium.launch({ headless: true, executablePath: process.env.QTRADES_BROWSER_QA_EXECUTABLE || undefined });
    context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, serviceWorkers: "block" });
    await context.route("**/*", route => {
      if (new URL(route.request().url()).origin !== origin) { external.push(route.request().url()); return route.abort(); }
      return route.continue(); // Leave every normal local poll enabled.
    });
    page = await context.newPage(); page.setDefaultTimeout(12000);
    page.on("pageerror", error => errors.push(error.message));
    page.on("request", request => { const u = new URL(request.url()); if (u.pathname.startsWith("/api/") && requests.length < 2000) requests.push({ method: request.method(), path: u.pathname, query: u.search }); });
    const qa = async action => { const r = await context.request.post(`${origin}/__qa/${action}`, { headers: { "x-qa-token": token } }); assert.equal(r.status(), 200, `${action}: ${await r.text()}`); return r.json(); };
    const probe = async () => { const r = await context.request.get(`${origin}/__qa/probe`, { headers: { "x-qa-token": token } }); assert.equal(r.status(), 200); return r.json(); };
    const until = async (predicate, label, bound = 45000) => { const end = Date.now() + bound; while (Date.now() < end) { const p = await probe(); assert.deepEqual(p.state.errors, [], `${label}: background failure`); if (predicate(p)) return p; await sleep(500); } throw new Error(`Timed out: ${label}`); };
    const text = () => page.locator("main").innerText();
    await page.goto(origin); await page.getByRole("heading", { name: "Understand the work. Follow the evidence." }).waitFor();
    phase = "five destinations and setup";
    for (const label of ["Overview", "Research", "Accounts & Results", "Markets", "Settings"]) assert(await page.getByRole("link", { name: label === "Accounts & Results" ? /^Accounts & Results/ : label, exact: label !== "Accounts & Results" }).isVisible());
    assert.equal((await probe()).posts.length, 0);
    await page.getByRole("link", { name: "Review research setup", exact: true }).click();
    await page.getByLabel("Local profile folder").waitFor();
    assert(await page.getByRole("button", { name: "Start supervised paper research", exact: true }).isDisabled());
    const p0 = await probe();
    await page.getByLabel("Local profile folder").fill(p0.profile_directory);
    await page.getByRole("button", { name: "Review existing profile", exact: true }).click();
    await page.getByRole("heading", { name: "New paper research permission" }).waitFor();
    await page.getByLabel("Approve this reviewed recurring scope and save its connection paused.").check();
    await page.getByRole("button", { name: "Save reviewed paper configuration", exact: true }).click();
    await page.getByText(/needs an application restart/).waitFor();
    assert.equal((await probe()).software_callbacks, 0);
    await page.screenshot({ path: path.join(directory, "setup-paused-desktop.png"), fullPage: true });
    await qa("restart-model"); await page.reload();
    await page.getByLabel(/Resume this saved comparison policy/).check();
    await page.getByLabel("I reviewed this saved scope and the startup actions above.").check();
    await qa("refuse");
    await page.getByRole("button", { name: "Start supervised paper research", exact: true }).click();
    await page.getByText(/Startup rejected: Synthetic precommit refusal/).waitFor();
    assert.equal((await probe()).software_callbacks, 0);
    // Re-review current saved choices after a deterministic rejection.
    await page.getByLabel(/Resume this saved comparison policy/).check();
    await page.getByLabel("I reviewed this saved scope and the startup actions above.").check();
    await qa("lost_ack");
    await page.getByRole("button", { name: "Start supervised paper research", exact: true }).click();
    await page.getByText(/saved as enabled/).waitFor();
    groups.push("paused metadata-only model configuration, required reload, reviewed startup refusal and lost acknowledgment reconciliation");
    const afterStart = await probe();
    assert.equal(afterStart.posts.filter(x => x.path === "/api/research/supervised-start").length, 2);
    phase = "hands-off background comparison";
    await page.getByRole("link", { name: "See current operation" }).click();
    const active = await until(p => p.tasks.some(t => t.stage === "outcome") && Object.values(p.trials).some(t => t.status === "active") && p.state.financial_ticks > afterStart.state.financial_ticks, "native worker to admitted pair and continuing financial tick", 90000);
    const original = active.tasks.find(t => t.stage === "outcome").id;
    const trial = Object.values(active.trials).find(t => t.status === "active");
    assert(active.software_callbacks >= 2); assert(active.state.financial_ticks > afterStart.state.financial_ticks);
    await page.getByText("Waiting for the comparison result").waitFor({ timeout: 20000 });
    const pollBefore = requests.filter(r => r.path === "/api/research/overview").length;
    await sleep(8500);
    assert(requests.filter(r => r.path === "/api/research/overview").length > pollBefore);
    await page.screenshot({ path: path.join(directory, "overview-waiting-desktop.png"), fullPage: true });
    await qa("mature");
    const done = await until(p => p.tasks.some(t => t.id === original && t.status === "done"), "mature outcome and lesson", 25000);
    assert.equal(done.software_callbacks, 3);
    groups.push("automatic actual worker/preparation/evaluation/review/inbox/native funding, waiting overview, unsuppressed polling and independent financial ticks");
    phase = "original result and archive/restart continuation";
    await qa("archive-restart-successor");
    const reopened = await until(p => p.successor && p.tasks.some(t => t.id === p.successor && t.stage !== "idea"), "same selected successor after cold reopen", 25000);
    assert.equal(reopened.original_done.result.outcome.body.outcome, "low_information");
    assert.equal(reopened.before_archive.context.pattern_learning.predecessor_task, original);
    assert.equal(reopened.before_archive.context.pattern_method.method_id, "p1");
    await page.goto(`${origin}/#research?task=${original}`);
    await page.getByRole("heading", { name: "Recorded comparison: low_information" }).waitFor();
    await page.getByRole("region", { name: "Linked next investigations" }).waitFor();
    const nextLink = page.locator(`a[href="#research?task=${reopened.successor}"]`).first();
    await nextLink.click(); await page.waitForURL(`**/#research?task=${reopened.successor}`);
    await page.goBack(); await page.waitForURL(`**/#research?task=${original}`);
    await page.getByRole("heading", { name: "Recorded comparison: low_information" }).waitFor();
    await page.screenshot({ path: path.join(directory, "investigation-result-desktop.png"), fullPage: true });
    groups.push("mature first → select p1 successor → archive original → reopen registry/worker → advance same successor; exact source/result/lesson links and Back");
    phase = "frozen-rule qualification and unknown funding acknowledgment";
    await page.getByRole("link", { name: "Open this matched comparison and account evidence" }).click();
    const retained = page.getByRole("region", { name: "Selected saved paper comparison" });
    await retained.getByRole("heading", { name: "low information", exact: true }).waitFor();
    assert((await text()).includes("After execution and declared operating costs"));
    await retained.getByText("Review prospective paper qualification", { exact: true }).click();
    await retained.getByLabel("Approve the frozen source, matched incumbent and separate hypothetical pair.").check();
    await qa("lost_ack");
    await retained.getByRole("button", { name: "Fund reviewed prospective paper pair", exact: true }).click();
    await retained.getByText("The original admission is confirmed. The same prospective pair continues; no duplicate funding was created.").waitFor();
    const funded = await probe();
    const candidate = Object.entries(funded.accounts).find(([n, a]) => a.qualification_source?.trial_id === trial.id && a.campaign_id === "forward-research");
    assert(candidate); const candidateName = candidate[0];
    assert.equal(Object.values(funded.accounts).filter(a => a.qualification_source?.trial_id === trial.id).length, 1);
    await retained.getByRole("link", { name: "Open this candidate’s qualification record" }).click();
    await page.getByLabel("Forward candidate").waitFor();
    assert.equal(await page.getByLabel("Forward candidate").inputValue(), candidateName);
    await page.getByRole("button", { name: "Inspect and retain forward comparison", exact: true }).click();
    await page.getByRole("heading", { name: "No promotion", exact: true }).waitFor();
    assert((await text()).includes("28"));
    assert(await page.getByRole("button", { name: "Approve paper incumbent designation" }).isDisabled());
    groups.push("original frozen RuleSpec → separately funded native prospective pair; unknown acknowledgment recovers same pair; synthetic/insufficient prospective evidence refuses promotion");
    phase = "account context across tabs, reload and Back";
    await page.getByRole("link", { name: "Performance & costs", exact: true }).click();
    const economics = page.getByRole("region", { name: "Whole-account economics", exact: true });
    const economicsAccount = economics.getByRole("combobox", { name: "Account", exact: true });
    assert.equal(await page.getByLabel("Performance account", { exact: true }).inputValue(), candidateName);
    assert.equal(await economicsAccount.inputValue(), candidateName);
    await page.getByLabel("Performance account", { exact: true }).selectOption("primary");
    await page.waitForFunction(() => document.querySelector("#account-economics select").value === "primary");
    assert(new URLSearchParams(page.url().split("?")[1]).get("view") === "performance");
    assert(!new URLSearchParams(page.url().split("?")[1]).has("trial"));
    await page.goBack(); assert.equal(await page.getByLabel("Performance account", { exact: true }).inputValue(), candidateName);
    assert.equal(await economicsAccount.inputValue(), candidateName);
    await economicsAccount.selectOption("primary");
    await page.waitForFunction(() => document.querySelector("#performance-account").value === "primary");
    assert.equal(new URLSearchParams(page.url().split("?")[1]).get("view"), "performance");
    assert(!new URLSearchParams(page.url().split("?")[1]).has("trial"));
    await page.goBack(); assert.equal(await economicsAccount.inputValue(), candidateName);
    await page.reload(); assert.equal(await economicsAccount.inputValue(), candidateName);
    assert.equal(await page.getByLabel("Performance account", { exact: true }).inputValue(), candidateName);
    await page.getByRole("link", { name: "Positions & orders", exact: true }).click();
    assert.equal(await page.getByRole("combobox", { name: "Trade account", exact: true }).inputValue(), candidateName);
    await page.reload(); assert.equal(await page.getByRole("combobox", { name: "Trade account", exact: true }).inputValue(), candidateName);
    await page.getByRole("button", { name: "Positions & pending", exact: true }).click();
    assert.equal(await page.getByRole("combobox", { name: "Account", exact: true }).inputValue(), candidateName);
    await page.getByRole("button", { name: "Journal", exact: true }).click();
    assert.equal(await page.getByRole("combobox", { name: "Journal account", exact: true }).inputValue(), candidateName);
    await page.goto(`${origin}/#accounts?account=${trial.candidate}&trial=${trial.id}`);
    await page.getByRole("region", { name: "Selected retained paper account" }).waitFor();
    assert((await text()).includes("Hypothetical funding"));
    await page.goto(`${origin}/#accounts?view=comparisons&trial=lab-${"f".repeat(24)}`);
    await page.getByText(/The original saved comparison is unavailable/).waitFor();
    await page.goto(`${origin}/#accounts?account=missing-original`);
    await page.getByText(/This original account is unavailable/).waitFor();
    for (const missing of ["missing-original", "constructor", "__proto__", "toString"]) {
      await page.goto(`${origin}/#accounts?account=${missing}`);
      await page.getByText(/This original account is unavailable/).waitFor();
      await page.getByRole("link", { name: "Performance & costs", exact: true }).click();
      await page.getByText(`Economics for ${missing} are unavailable`, { exact: false }).waitFor();
      assert.equal(await economicsAccount.inputValue(), missing);
      assert.equal(await page.getByLabel("Performance account", { exact: true }).inputValue(), missing);
      assert.equal(await economics.getByRole("button", { name: "Save future cost assumptions", exact: true }).count(), 0);
      assert.equal(await economics.locator("dl.economics-values").count(), 0);
      await page.getByRole("link", { name: "Positions & orders", exact: true }).click();
      await page.getByRole("button", { name: "Positions & pending", exact: true }).click();
      assert.equal(await page.getByRole("combobox", { name: "Account", exact: true }).inputValue(), missing);
      await page.getByText(/Current holdings for this exact account are unavailable/).waitFor();
      await page.getByRole("button", { name: "Journal", exact: true }).click();
      assert.equal(await page.getByRole("combobox", { name: "Journal account", exact: true }).inputValue(), missing);
      await page.getByText("Account history and balances changed", { exact: true }).click();
      await page.getByText("Account history could not load. Retry when connected.", { exact: true }).waitFor();
    }
    groups.push("selected active/retired accounts, shared chart/economics scope in both directions, performance/trade/positions/journal account context, view-preserving select, foreign trial cleared, reload/Back and explicit unknown exact identities without another account's settings");
    phase = "read outage, narrow layout and recovery";
    await page.goto(`${origin}/#overview`); await qa("outage");
    await page.getByText(/Current operation is unavailable\. Reconnect/).waitFor({ timeout: 20000 });
    await page.setViewportSize({ width: 420, height: 900 });
    await page.screenshot({ path: path.join(directory, "overview-outage-narrow.png"), fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2));
    await qa("restore");
    await page.getByText(/Current operation is unavailable\. Reconnect/).waitFor({ state: "hidden", timeout: 20000 });
    await page.keyboard.press("Tab"); assert(await page.evaluate(() => document.activeElement.tagName !== "BODY"));
    await page.screenshot({ path: path.join(directory, "overview-recovered-narrow.png"), fullPage: true });
    groups.push("current-read failure/recovery while ordinary polling and background owners continue; narrow geometry and keyboard focus");
    receipt.final = await probe();
    assert(receipt.final.prefix_preserved && receipt.final.balanced && receipt.final.source_hashes_unchanged);
    assert.deepEqual(receipt.final.state.errors, []); assert.deepEqual(errors, []); assert.deepEqual(external, []);
    assert.equal(receipt.final.model_calls, 0);
    save("final-probe.json", receipt.final);
    receipt.passed = true;
  } catch (error) {
    failure = error; receipt.passed = false; receipt.failure = { phase, message: error.message, stack: error.stack };
    if (page && !page.isClosed()) { await page.screenshot({ path: path.join(directory, "failure.png"), fullPage: true }).catch(() => {}); fs.writeFileSync(path.join(directory, "failure.txt"), await page.locator("body").innerText().catch(() => "Unavailable")); }
  } finally {
    clearTimeout(deadline); save("workflow.json", receipt);
    if (context) await context.close(); if (browser) await browser.close();
  }
  console.log(JSON.stringify({ passed: receipt.passed, groups, failure: receipt.failure, output: directory }));
  if (failure) process.exitCode = 1;
})();
