import { useEffect, useState } from "react";
import { ReplayPanel } from "./ReplayPanel";

type Status = { state: string; reason?: string; plan?: { root: string; temporary_bytes: number; research_bytes: number; free_reserve_bytes: number; scratch_bytes: number }; temporary_bytes?: number; research_bytes?: number; free_bytes?: number; protected_bytes?: number; maturity_headroom_bytes?: number; pending_segments?: number; last_success?: number; next_due?: number; capture_bytes_per_second?: number; estimated_temporary_runway_seconds?: number; read_bytes?: number; written_bytes?: number; reclaimed_bytes?: number; last_capture?: number; latest_reference?: string; full_omitted?: number; compact_omitted?: number; queued_packets?: number };
const bytes = (v?: number) => v == null ? "Unavailable" : `${(v / 1e9).toLocaleString(undefined, { maximumFractionDigits: 4 })} GB`;
const when = (v?: number) => v == null ? "No successful receipt" : new Date(v * 1000).toLocaleString();
export function ResearchStoragePanel() {
  const [status, setStatus] = useState<Status | null>(null);
  const [root, setRoot] = useState("G:\\Projects\\Q-Trades-Data");
  const [error, setError] = useState<string | null>(null);
  const [identity, setIdentity] = useState<string | null>(null);
  const [target, setTarget] = useState<{ free_bytes: number } | null>(null);
  const [busy, setBusy] = useState(false);
  const [evidence, setEvidence] = useState<unknown>(null);
  const selectedCapture = evidence as { reference?: string; payload?: { kind?: string } } | null;
  useEffect(() => { let stopped = false; const read = async () => { try { const r = await fetch("/api/research/storage", { cache: "no-store", signal: AbortSignal.timeout(5000) }); if (!r.ok) throw new Error("Storage status unavailable"); const value = await r.json(); if (!stopped) setStatus(value); } catch (e) { if (!stopped) setError(String(e)); } }; void read(); const timer = setInterval(read, 15000); return () => { stopped = true; clearInterval(timer); }; }, []);
  async function inspect() { setBusy(true); try { const r = await fetch("/api/research/storage/target?root=" + encodeURIComponent(root)); const value = await r.json(); if (!r.ok) throw new Error(value.detail); setIdentity(value.identity); setTarget(value); setError(null); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  async function declare() { setBusy(true); try { const r = await fetch("/api/research/storage/plan", { method: "POST", headers: { "Content-Type": "application/json", "X-Local-Operator": "1" }, body: JSON.stringify({ root, volume_identity: identity }) }); const value = await r.json(); if (!r.ok) throw new Error(value.detail); setStatus({ state: "awaiting_worker", plan: value.plan, reason: value.activation }); setError(null); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  return <section className="research-activity" aria-label="Research storage"><h2>Research storage</h2>
    <p><strong>{status?.state.replaceAll("_", " ") ?? "Reading storage…"}</strong> · {status?.reason}</p>
    {status?.plan && <p>Queued capture: {status.queued_packets ?? "Unavailable"} / 8. Omitted full capture attempts: {status.full_omitted ?? "Unavailable"}; compact inputs: {status.compact_omitted ?? "Unavailable"}. Missing coverage is retained as unknown.</p>}
    <p>Temporary capture: {bytes(status?.temporary_bytes)} / {bytes(status?.plan?.temporary_bytes ?? 100e9)}. Retained research: {bytes(status?.research_bytes)} / {bytes(status?.plan?.research_bytes ?? 100e9)}. Quotas use decimal GB; each default tier is 100,000,000,000 bytes.</p>
    {status?.plan && <><p>Owned root: {status.plan.root}<br />Free volume space: {bytes(status.free_bytes)} · Required free reserve: {bytes(status.plan.free_reserve_bytes)} · Declared scratch reserve: {bytes(status.plan.scratch_bytes)}.<br />Due-outcome headroom within these quotas: {bytes(status.maturity_headroom_bytes)}. Space for a complete two-segment transfer remains reserved.</p><p>Protected/pending detail: {bytes(status.protected_bytes)} · Unprocessed segments: {status.pending_segments ?? "Unavailable"}. Capture rate: {status.capture_bytes_per_second?.toFixed(1) ?? "Unavailable"} bytes/s · Estimated temporary runway: {status.estimated_temporary_runway_seconds == null ? "Unavailable" : `${(status.estimated_temporary_runway_seconds / 3600).toFixed(1)} hours`}.</p><p>Last capture: {when(status.last_capture)} · Last successful maintenance: {when(status.last_success)} · Next maintenance: {when(status.next_due)}.<br />Last cycle read {bytes(status.read_bytes)}, wrote {bytes(status.written_bytes)}, reclaimed {bytes(status.reclaimed_bytes)}.</p></>}
    <p>Housekeeping runs every two hours and on capacity pressure. Detailed segments retain exact evidence with checksums and lossless compression. Sampled numerical rollups support descriptive research. Temporary expiration starts after seven days and follows verified retention; it is extended for protected dependencies. The retained tier stops at capacity and requires an export/capacity decision. Drive failure pauses capture with visible missed coverage; financial position management continues.</p>
    {status?.latest_reference && <button onClick={() => { void fetch("/api/research/storage/evidence?reference=" + encodeURIComponent(status.latest_reference!)).then(async r => { const value = await r.json(); if (!r.ok) throw new Error(value.detail); setEvidence(value); }).catch(e => setError(String(e))); }}>Reopen exact latest capture</button>}
    {evidence != null && <details open className="lab-inspection"><summary>Exact capture evidence</summary><button onClick={() => setEvidence(null)}>Close capture</button><pre>{JSON.stringify(evidence, null, 2)}</pre></details>}
    {selectedCapture?.payload?.kind === "decision" && <ReplayPanel recordId={selectedCapture.reference} />}
    {!status?.plan && <details><summary>Declare the external storage plan</summary><label>Owned data root<input value={root} onChange={e => { setRoot(e.target.value); setIdentity(null); setTarget(null); }} /></label><button disabled={busy} onClick={() => void inspect()}>Inspect target volume</button>{target && <p>Observed free space: {bytes(target.free_bytes)}. Volume identity is bound to this declaration.</p>}<button disabled={busy || !identity} onClick={() => void declare()}>Save 100 GB + 100 GB storage plan</button><p>Saving declares paths for the next paper-worker startup. Activation and installation are separate operator actions. Existing capped evidence and the financial journal retain their paths and history.</p></details>}
    {error && <p role="alert" className="warning">{error}</p>}
  </section>;
}
